# Generated by Django 4.0.7 on 2022-08-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_remove_result_maths_result_value_error_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['id']},
        ),
    ]
