# Generated by Django 3.2.15 on 2022-08-26 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookrenthistory_back_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 4, 22, 55, 192395)),
        ),
    ]
