# Generated by Django 3.2.15 on 2022-08-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20220826_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 18, 17, 35, 580274)),
        ),
    ]
