# Generated by Django 3.2.15 on 2022-08-26 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20220826_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 20, 38, 58, 510916)),
        ),
    ]
